[build]
builder = "NIXPACKS"
buildCommand = "cd scraper && pip install -r requirements.txt"

[deploy]
startCommand = "python scraper/mbs_scraper.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[service]
schedule = "0 */6 * * *"  # Runs every 6 hours 